### ISSUE TITLE
[Feature issue] There’s no time checker for the start-end time of the activity and the time listed in the Comprehensive Program Design (Page 2 of pre-acts form).

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#41]
Description
- The pre-activity form still proceeds to the next page even though the time in the Comprehensive Program Design is not within the timeframe of the whole activity or even though the start & end time is invalid.

Build / Platform
- Build 3
- Windows 10 / Google Chrome

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password.
- Username: phead_catch@dlsu.edu.ph / phead_gas@dlsu.edu.ph
- Password: password
- Click “Login”.
- Enter the Start Time of the activity as “11:00 AM”
- Enter the End Time of the activity as “1:00 PM”
- Enter the Start Time of the Comprehensive Program Design as “5:00 AM”
- Enter the End Time of the Comprehensive Program Design as 9:00 AM”
- Fill the remaining fields with correct information
- Click “Next”

Actual Result
- The pre-activity form proceeds to the next page.

Expected Result
- The pre-activity form does not proceed to the next page because of invalid time in the Comprehensive Program Design.

**Comment by angeloablaza** [comment]
resolved & checked by QA team as of 13/12/18

**Comment by afsantooos** [comment]
The input below is accepted. The error checking of the time only checks if the first and last time is consistent with the start/end of the activity. 

![image](https://user-images.githubusercontent.com/36391115/49946769-a1057980-ff2a-11e8-8a56-386b4375692c.png)

**Comment by angeloablaza** [comment]
resolved & checked by QA team as of 14/12/18
