### ISSUE TITLE
[User Testing Issue] should have numbering when filling out the form (to be consistent with the one in viewing form)

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#47]
Description
- When viewing a form via “View Activity” that parts are no longer numbered as opposed to how they were numbered in “Create Form”

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password.
- Username: catch_president@dlsu.edu.ph
- Password: password
- Click “Login”.
- Select a form form the dashboard
- Click “View Activity” from Quick View

Actual Result
- No numbering present	

Expected Result
- Numbering mirroring the “Create a Form” one’s is present

**Comment by angeloablaza** [comment]
resolved & checked by QA team as of 14/12/18
