### ISSUE TITLE
[Interface Issue] Buttons inside view form is not consistent with accept and reject of quick view

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#48]
Description
- Full Reject, Reject, & Approve’s colors are not consistent with the other approve & reject buttons. 

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password.
- Username: catch_president@dlsu.edu.ph
- Password: password
- Click “Login”.
- Select a form form the dashboard
- Click “View Activity” from Quick View

Actual Result
- The three buttons all have the same color

Expected Result
- The three buttons would have the same colors they have in the Quick View

**Comment by Rolopens** [comment]
Please double check this issue. This was fixed on December 15, 2018

**Comment by afsantooos** [comment]
resolved & checked by QA team as of 13/12/18
