### ISSUE TITLE
[Feature issue] Remaining Balance in VII. Organizational Funds is always NaN

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#53]
Description
- No matter what values are present in Part V, VI, and VII, the Remaining Balance in VII. Organizational Funds is always NaN.

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password:
- Click “Login”
- Click “Create New Form”
- Fill out the first page of the form with valid details
- Click “Next”
- Fill out the second page of the form with valid details

Actual Result
- Remaining Balance in VII. Organizational Funds is “NaN”

Expected Result
- Remaining Balance in VII. Organizational Funds should be a numerical value in response to the input in part V, VI, and VII.

**Comment by angeloablaza** [comment]
resolved & checked by QA team as of 13/12/18
