### ISSUE TITLE
[Feature issue] No checker if Part VIII: Projected Expenses matches Part V (Breakdown of Expenses).

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#54]
Description
- There is no checker if the input in part V (Breakdown of Expenses) matches the input in part VIII (Projected Expenses)

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password:
- Username: phead_catch@dlsu.edu.ph
- Password: password
- Click “Login”
- Click “Create New Form”
- Fill out the first page of the form with valid details
- Click “Next”
- For Part V, input the following: (Materials: “Apple”, Quantity: 10, Unit Cost: 20)
- For Part VIII Projected Expenses, input the following: (Materials: “Orange”, Quantity: 20, Unit Cost: 25)
- Fill out the rest of the page with valid details
- Click “Next”

Actual Result
- The pre-activity form proceeds to the next page

Expected Result
- The pre-activity form does not proceed to the next page.

**Comment by pozrah08** [comment]
[Interface Issue] There are two error messages of "Projected Expenses must be equal to Breakdown of Expenses."

![image](https://user-images.githubusercontent.com/34395927/49940690-3731a380-ff1b-11e8-8fd5-8a17d4e320cd.png)

Inputs:
![image](https://user-images.githubusercontent.com/34395927/49940791-8bd51e80-ff1b-11e8-93a4-758a67ceed0f.png)
![image](https://user-images.githubusercontent.com/34395927/49940811-a9a28380-ff1b-11e8-8692-f1852411ad9c.png)

**Comment by afsantooos** [comment]
Initial issue is solved but there is a new issue because of the "fix". New issue is commented by @pozrah08 above.

**Comment by angeloablaza** [comment]
resolved & checked by QA team as of 14/12/18
