### ISSUE TITLE
[Feature issue] In Part IX. Provisions for Profit and Loss, user can put one person responsible and the form will still submit. 

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#55]
Description
- The project head can still submit the form even though there is only one person responsible (Part IX) in the form.

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password:
- Username: phead_catch@dlsu.edu.ph
- Password: password
- Click “Login”
- Click “Create New Form”
- Fill out the form with valid details except for Part IX
- Fill out “Name of Person Responsible” and “Position” on the left side with valid details
- Click “Submit”
- Click “Submit” in the modal

Actual Result
- The pre-activity form is created.

Expected Result
- The pre-activity form should not be created.

**Comment by pozrah08** [comment]
[Feature Issue] When the bug above happens, it also bypasses the checker of Part V. Breakdown of Expenses and Part VIII. Projected Expenses

![image](https://user-images.githubusercontent.com/34395927/49942576-aa89e400-ff20-11e8-997e-203b8f6b1729.png)

**Comment by afsantooos** [comment]
Initial issue is solved but there is a new issue because of the "fix". New issue is commented by @pozrah08 above.

**Comment by afsantooos** [comment]
resolved & checked by QA team as of 13/12/18
