### ISSUE TITLE
[Feature Issue] Date of Event filter does not work as intended

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#60]
Description
- Date of Event (Newest and Oldest first) does not filter as expected.

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password:
- Username: phead_catch@dlsu.edu.ph
- Password: password
- Click “Login”
- Click “Date of Event (Oldest First/Newest First)

Actual Result
- The dates of events are not sorted properly. 
- Ex: If sorted by date of events (newest first) then the order of dates looks like this: December 18, December 19, December 13

Expected Result
- The forms are sorted by the date of the activity. Ex: If sorted by newest first, then December 13, 2018 must be on top of December 15, 2018. If sorted by oldest first, then December 15, 2018 must be on top of December 13, 2018.

**Comment by angeloablaza** [comment]
resolved & checked by QA team as of 14/12/18
