### ISSUE TITLE
[Interface issue] When editing a rejected form, fields involving finance is always blank by default if the “old form” has inputs of 4 or more digits.

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#63]
Description
- When a project head edits a rejected form for revisions, the following fields will be shown as blank by default if the old inputs had 4 or more digits:
- Part V. Breakdown of Expenses: Unit Cost
- Part VI. Source of Funds: Participants Fee, Others
- Part VII. Organizational Funds: Operational Fund
- Part VIII. Projected Income:  (Projected Revenue & Projected Expenses) Selling Price, Participants Fee/Donation/Sponsorships

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password:
- Username: phead_catch@dlsu.edu.ph
- Password: password
- Click “Login”
- Click “Create New Form”
- Fill out the first two pages with valid details
- Click “Next”
- Enter “1000” for all numeric fields 
- Fill the remaining fields with valid inputs
- Click “Submit”
- Logout
- Type in valid username and password:
- Username: oplog_checker@dlsu.edu.ph
- Password: password
- Click “Login”
- Select the form that was just submitted by phead_catch@dlsu.edu.ph
- Click “Reject Activity”
- Enter a valid input as its reason (ex. “Too expensive”).
- Click “Reject”
- Logout
- Type in valid username and password:
- Username: phead_catch@dlsu.edu.ph
- Password: password
- Click “Login”
- Select the rejected form
- Click “View Activity”
- Click “Edit”
- Navigate to the third page (Click “Next” twice)

Actual Result
- The following fields are blank instead of having “1000” as a default input:
- Part V. Breakdown of Expenses: Unit Cost
- Part VI. Source of Funds: Participants Fee, Others
- Part VII. Organizational Funds: Operational Fund
- Part VIII. Projected Income:  (Projected Revenue & Projected Expenses) Selling Price, Participants Fee/Donation/Sponsorships

Expected Result
- All numerical fields have 1000 as its default input.

**Comment by angeloablaza** [comment]
**Still blank as of 3:00am fix**
VI. Source of Funds -> Others
VII. Organizational Funds ->Operational Fund, Participants Fee/Donation/Sponsorships
 VIII. Projected Income ->Less: Projected Expenses
