### ISSUE TITLE
[Interface issue] When editing a form, there are no decimal places shown in some fields.

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#64]
Description
- When a project head edits a rejected form for revisions, the following fields will not have a decimal place (ex. .00) by default:
- Part VI. Source of Funds: Organizational Funds
- Part VII. Organizational Funds: Depository Fund

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password
- Click “Login”
- Click “Create New Form”
- Fill out the first two pages with valid details
- Click “Next”
- Enter “999” for all numeric fields 
- Fill the remaining fields with valid inputs
- Click “Submit”
- Logout
- Type in valid username and password:
- Username: oplog_checker@dlsu.edu.ph
- Password: password
- Click “Login”
- Select the form that was just submitted by phead_catch@dlsu.edu.ph
- Click “Reject Activity”
- Enter a valid input as its reason (ex. “Too expensive”).
- Click “Reject”
- Logout
- Type in valid username and password:
- Username: phead_catch@dlsu.edu.ph
- Password: password
- Click “Login”
- Select the rejected form
- Click “View Activity”
- Click “Edit”
- Navigate to the third page (Click “Next” twice)

Actual Result
- There are no decimal places shown in some fields

Expected Result
- There are values in all fields

**Comment by angeloablaza** [comment]
resolved & checked by QA team as of 14/12/18
