### ISSUE TITLE
[Interface Issue] When the “Type of the Activity” is “Off-Campus Activity”, it does not properly show in quick view.

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#66]
Description
- If an activity’s “Type of the Activity” is “Off-Campus Activity”, it only shows as “Off” when viewed in quick view.

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password
- Click “Login”
- Click “Create New Form”
- Have the “Type of the Activity” as “Off-Campus Activity” under SLIFE
- Fill out the rest of the form with valid details
- Click “Submit”
- Select the newly created form

Actual Result
- The “Type of the Activity” of the pre-activity form is “Off” when viewed via quick view.

Expected Result
- The “Type of the Activity” of the pre-activity form is “Off-Campus Activity” when viewed via quick view.

**Comment by Rolopens** [comment]
This was corrected with the commit 'Fixed issue #54 and #65 and added files for modularity (not yet implemented)'.

**Comment by afsantooos** [comment]
resolved & checked by QA team as of 13/12/18
