### ISSUE TITLE
[Feature Issue] When you cancel your submission via the confirmation modal, leave any field blank in the third page of the pre-activity, the project head can still proceed with the submission the next time they click "Submit"

### ISSUE THREAD

**Issue by afsantooos** [Rolopens/DLSU_OPPS_FormApproval_Preacts#67]
Description
- Cancelling the submission of the form and then having no input for any field in the third page, will still allow the project head to submit the form even though there are error messages.

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password:
- Username: phead_catch@dlsu.edu.ph
- Password: password
- Click "Create New Form"
- Fill out the form with valid details
- Click "Submit"
- Click "Close" in the "Confirm Action" message.
- Erase the input of any field in the third page (Part V ~ Part IX)
- Click "Submit"

Actual Result
- The pre-activity form can be submitted

Expected Result
- The pre-activity form cannot be submitted

**Comment by angeloablaza** [comment]
resolved & checked by QA team as of 14/12/18
