### ISSUE TITLE
[Feature Issue] When rejecting from Quick View, if user clicks reject without placing comments, modal closes, no error message/prompt

### ISSUE THREAD

**Issue by angeloablaza** [Rolopens/DLSU_OPPS_FormApproval_Preacts#69]
Description
- When a user rejects an activity from quick view, a modal appears for them to give comments, if this is left blank and the users clicks reject/full reject, no prompt is shown to fill up the field

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password.
- Username: catch_president@dlsu.edu.ph
- Password: password
- Click “Login”.
- Select a form
- Click “Reject” from Quick View
- Leave the text area blank
- Click Reject or Full Reject

Actual Result
- Modal closes

Expected Result
- Error message is shown prompting the user to place comment/s

**Comment by angeloablaza** [comment]
resolved & checked by QA team as of 14/12/18

**Comment by pozrah08** [comment]
Would it be possible if the error message/prompt to be similar to when a checker rejects w/o giving a message at "View Activity"? Such as:
![image](https://user-images.githubusercontent.com/34395927/49955619-352d0c00-ff3e-11e8-9cf1-5db5ab46e75a.png)

Just for consistency :)
