### ISSUE TITLE
[Feature Issue] When editing the type of the activity, both SLIFE and DAAM can see the activity in their list of activities.

### ISSUE THREAD

**Issue by angeloablaza** [Rolopens/DLSU_OPPS_FormApproval_Preacts#70]
Description
- When the type of an activity changes, the original checker (slife_approver / daam_aps) it went through can still have the activity in its list of activities.

Build/Platform
- Build 3
- Google Chrome / Windows 10

Steps to Reproduce
- Navigate to application (localhost:3000)
- Type in valid username and password:
- Click “Create New Form”
- Have the type of the activity as “Assistance” Through CSO/DAAM
- Fill out the rest of the form with valid details
- Submit the form
- Logout
- Type in valid username and password:
- Username: oplog_checker@dlsu.edu.ph
- Password: password
- Click “Login”
- Select the form that was submitted by phead_catch@dlsu.edu.ph
- Click “Approve Activity”
- Click “Approve”
- Logout
- Type in valid username and password:
- Username: otreas_checker@dlsu.edu.ph
- Password: password
- Click “Login”
- Select the form that was submitted by phead_catch@dlsu.edu.ph
- Click “Approve Activity”
- Click “Approve”
- Logout
- Type in valid username and password:
- Username: catch_president@dlsu.edu.ph
- Password: password
- Select the form that was submitted by phead_catch@dlsu.edu.ph
- Click “Approve Activity”
- Click “Approve”
- Logout
- Type in valid username and password:
- Username: ccs_president@dlsu.edu.ph
- Password: password
- Click “Login”
- Select the form that was submitted by phead_catch@dlsu.edu.ph
- Click “Approve Activity”
- Click “Approve”
- Logout
- Type in valid username and password:
- Username: daam_aps@dlsu.edu.ph
- Password: password
- Click “Login”
- Select the form that was submitted by phead_catch@dlsu.edu.ph
- Click “Reject Activity”
- Type in a valid input (Ex. “Change the type of the activity”)
- Click “Reject”
- Logout
- Type in valid username and password:
- Username: phead_catch@dlsu.edu.ph
- Password: password
- Click “Login”
- Select the form
- Click “View Activity”
- Click “Edit”
- Change the type of the activity to “Outreach” Through SLIFE
- Submit the form
- Logout
- Type in valid username and password:
- Username: daam_aps@dlsu.edu.ph
- Password: password
- Click “Login”

Actual Result
- The activity is in the list of activities of daam_aps@dlsu.edu.ph

Expected Result
- The activity is not in the list of activities of daam_aps@dlsu.edu.ph

**Comment by afsantooos** [comment]
resolved & checked by QA team as of 14/12/18
